name: Deploy Laravel to Hostinger

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write SSH key to file
        run: |
          echo "$DEPLOY_KEY" > /tmp/deploy_key
          chmod 600 /tmp/deploy_key
        env:
          DEPLOY_KEY: ${{ secrets.HOSTINGER_SSH_KEY }}

      # Deploy do Laravel (exceto public) para a raiz do domínio
      - name: Deploy Laravel project (exceto public) para Hostinger
        run: |
          rsync -avz --exclude 'public/' --exclude '.git/' --exclude '.github/' \
            -e "ssh -o StrictHostKeyChecking=no -p 65002 -i /tmp/deploy_key" \
            ./ u855546018@147.93.37.133:/home/u855546018/domains/cassote.com/

      # Deploy do conteúdo da pasta public para public_html (sem --delete!)
      - name: Deploy public/ para public_html
        run: |
          rsync -avz \
            -e "ssh -o StrictHostKeyChecking=no -p 65002 -i /tmp/deploy_key" \
            ./public/ u855546018@147.93.37.133:/home/u855546018/domains/cassote.com/public_html/

      # Deploy do public_path.php para a raiz
      - name: Deploy custom public_path.php
        run: |
          rsync -avz \
            -e "ssh -o StrictHostKeyChecking=no -p 65002 -i /tmp/deploy_key" \
            ./public_path.php u855546018@147.93.37.133:/home/u855546018/domains/cassote.com/public_path.php

      # Deploy da pasta build diretamente para public_html/build (caso necessário)
      - name: Deploy build/ para public_html/build
        run: |
          rsync -avz \
            -e "ssh -o StrictHostKeyChecking=no -p 65002 -i /tmp/deploy_key" \
            ./public/build/ u855546018@147.93.37.133:/home/u855546018/domains/cassote.com/public_html/build/

      # Baixar Composer 2 no servidor
      - name: Download Composer 2
        run: |
          ssh -o StrictHostKeyChecking=no -p 65002 -i /tmp/deploy_key u855546018@147.93.37.133 '
            cd /home/u855546018/domains/cassote.com/ &&
            php -r "copy(\"https://getcomposer.org/composer-2.phar\", \"composer.phar\");"
          '

      # Comandos pós-deploy
      - name: Run SSH commands on Hostinger (Composer 2)
        run: |
          ssh -o StrictHostKeyChecking=no -p 65002 -i /tmp/deploy_key u855546018@147.93.37.133 '
            cd /home/u855546018/domains/cassote.com/ &&
            php composer.phar install --no-interaction --prefer-dist --optimize-autoloader &&
            php artisan config:cache &&
            php artisan route:cache
            # php artisan migrate --force
          '